// client-dashboard/src/app/components/notification/notification.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-notification',
  templateUrl: './notification.component.html'
})
export class NotificationComponent {
  @Input() message: string = '';
  @Input() type: 'success' | 'alert' | 'error' = 'success';
  @Input() duration: number = 3000;

  @Output() close = new EventEmitter<void>();

  visible = true;

  notificationClass = '';
  iconClass = '';

  ngOnInit() {
    this.notificationClass = this.getNotificationClass();
    this.iconClass = this.getIconClass();

    setTimeout(() => {
      this.closeNotification();
    }, this.duration);
  }

  getNotificationClass() {
    switch (this.type) {
      case 'success':
        return 'bg-green-500 text-white';
      case 'alert':
        return 'bg-yellow-500 text-white';
      case 'error':
        return 'bg-red-500 text-white';
      default:
        return 'bg-gray-500 text-white';
    }
  }

  getIconClass() {
    return 'bg-transparent text-white';
  }

  closeNotification() {
    this.visible = false;
    this.close.emit();
  }
}
<div *ngIf="visible"
    [ngClass]="['fixed top-4 right-6 rounded-lg px-4 py-2 shadow-lg transition-transform duration-300', notificationClass]"
    (click)="closeNotification()">
    <div class="flex items-center">
        <div [ngClass]="iconClass" class="mr-3 flex items-center justify-center rounded-full bg-opacity-25">
            <ng-container [ngSwitch]="type">
                <svg *ngSwitchCase="'success'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"
                    fill="currentColor" class="size-6">
                    <path fill-rule="evenodd"
                        d="M8.603 3.799A4.49 4.49 0 0 1 12 2.25c1.357 0 2.573.6 3.397 1.549a4.49 4.49 0 0 1 3.498 1.307 4.491 4.491 0 0 1 1.307 3.497A4.49 4.49 0 0 1 21.75 12a4.49 4.49 0 0 1-1.549 3.397 4.491 4.491 0 0 1-1.307 3.497 4.491 4.491 0 0 1-3.497 1.307A4.49 4.49 0 0 1 12 21.75a4.49 4.49 0 0 1-3.397-1.549 4.49 4.49 0 0 1-3.498-1.306 4.491 4.491 0 0 1-1.307-3.498A4.49 4.49 0 0 1 2.25 12c0-1.357.6-2.573 1.549-3.397a4.49 4.49 0 0 1 1.307-3.497 4.49 4.49 0 0 1 3.497-1.307Zm7.007 6.387a.75.75 0 1 0-1.22-.872l-3.236 4.53L9.53 12.22a.75.75 0 0 0-1.06 1.06l2.25 2.25a.75.75 0 0 0 1.14-.094l3.75-5.25Z"
                        clip-rule="evenodd" />
                </svg>
                <svg *ngSwitchCase="'alert'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                    class="size-6">
                    <path fill-rule="evenodd"
                        d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003ZM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75Zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
                        clip-rule="evenodd" />
                </svg>
                <svg *ngSwitchCase="'error'" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor"
                    class="size-6">
                    <path fill-rule="evenodd"
                        d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12ZM12 8.25a.75.75 0 0 1 .75.75v3.75a.75.75 0 0 1-1.5 0V9a.75.75 0 0 1 .75-.75Zm0 8.25a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5Z"
                        clip-rule="evenodd" />
                </svg>
            </ng-container>
        </div>
        <p class="text-sm font-medium my-0">{{ message }}</p>
    </div>
</div>

// barber-dashboard/src/components/Notification.jsx
import { useEffect } from "react";
import {
    CheckCircleIcon,
    ExclamationTriangleIcon,
    ExclamationCircleIcon,
} from "@heroicons/react/24/solid";

const typeStyles = {
    success: "bg-green-500 text-white",
    alert: "bg-yellow-500 text-white",
    error: "bg-red-500 text-white",
    default: "bg-gray-500 text-white",
};

const iconByType = {
    success: CheckCircleIcon,
    alert: ExclamationTriangleIcon,
    error: ExclamationCircleIcon,
};

export default function Notification({ message, type, duration = 3000, onClose }) {
    useEffect(() => {
        const id = setTimeout(() => onClose?.(), duration);
        return () => clearTimeout(id);
    }, [duration, onClose]);

    const Icon = iconByType[type] ?? iconByType.alert;

    return (
        <div
            className={[
                "fixed top-4 right-4 z-[9999] max-w-xs outline-2 px-4 py-2 rounded-lg",
                "transition-transform duration-300 cursor-pointer shadow-lg",
                typeStyles[type] || typeStyles.default,
            ].join(" ")}
            onClick={() => onClose?.()}
            role="alert"
        >
            <div className="flex items-center">
                <div className="mr-3 flex items-center justify-center rounded-full bg-opacity-25">
                    <Icon className="size-4" />
                </div>
                <p className="text-sm font-medium my-0">{message}</p>
            </div>
        </div>
    );
}
